import { useState, useRef } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import api from '../api';
import { format } from 'date-fns';
import { useClient } from '../context/ClientContext';
import SocialIcon, { getBrandColor } from '../components/SocialIcon';
import {
    Image as ImageIcon,
    Loader2,
    Sparkles,
    Pencil,
    Trash2,
    Eye,
    CheckCircle2,
    XCircle,
    Clock,
    ChevronRight,
    FileText,
    RefreshCw,
    Upload,
    Zap,
    Palette,
    Maximize2,
    X,
    RotateCcw
} from 'lucide-react';

export default function Drafts() {
    const { selectedClientId } = useClient();
    const queryClient = useQueryClient();
    const [selectedPost, setSelectedPost] = useState(null);
    const [isEditing, setIsEditing] = useState(false);
    const [editData, setEditData] = useState({ caption: '', poster_copy: '' });
    const [showRefineModal, setShowRefineModal] = useState(false);
    const [instruction, setInstruction] = useState('');
    const [scheduledAt, setScheduledAt] = useState('');
    const fileInputRef = useRef(null);
    const [isRegenerating, setIsRegenerating] = useState(false);
    const [isUploading, setIsUploading] = useState(false);
    const [isRecompositing, setIsRecompositing] = useState(false);
    const [showFullImage, setShowFullImage] = useState(false);

    const { data: posts = [], isLoading } = useQuery({
        queryKey: ['posts', selectedClientId],
        queryFn: () => api.get(`/posts?client_id=${selectedClientId}`).then(res => res.data),
        refetchInterval: 5000 // Poll so we see new drafts generated by the background engine
    });

    const drafts = posts.filter(p => p.status === 'draft');

    const updateMutation = useMutation({
        mutationFn: (data) => api.patch(`/posts/${selectedPost.id}`, data).then(res => res.data),
        onSuccess: (updated) => {
            toast.success('Draft Updated');
            setSelectedPost(updated);
            setIsEditing(false);
            queryClient.invalidateQueries(['posts']);
        }
    });

    const deleteMutation = useMutation({
        mutationFn: (id) => api.delete(`/posts/${id}`).then(res => res.data),
        onSuccess: () => {
            toast.success('Draft Deleted');
            setSelectedPost(null);
            queryClient.invalidateQueries(['posts']);
        }
    });

    const approveMutation = useMutation({
        mutationFn: (id) => api.patch(`/posts/${id}/approve`, { scheduled_at: scheduledAt }).then(res => res.data),
        onSuccess: () => {
            toast.success(scheduledAt ? 'Post Scheduled and Queued!' : 'Post Approved. Ready to publish!');
            setSelectedPost(null);
            setScheduledAt('');
            queryClient.invalidateQueries(['posts']);
        }
    });

    const rejectMutation = useMutation({
        mutationFn: (id) => api.patch(`/posts/${id}/reject`).then(res => res.data),
        onSuccess: () => {
            toast.success('Post Rejected');
            setSelectedPost(null);
            queryClient.invalidateQueries(['posts']);
        }
    });

    const refineMutation = useMutation({
        mutationFn: (data) => api.patch(`/posts/${selectedPost.id}/refine`, data).then(res => res.data),
        onSuccess: (updated) => {
            toast.success('Design & Copy Refined');
            setSelectedPost(updated);
            setShowRefineModal(false);
            setInstruction('');
            queryClient.invalidateQueries(['posts']);
        },
        onError: (err) => {
            toast.error('Refinement Failed: ' + (err.response?.data?.error || err.message));
        }
    });

    const startEdit = () => {
        setEditData({ caption: selectedPost.caption, poster_copy: selectedPost.poster_copy });
        setIsEditing(true);
    };

    const handleDelete = () => {
        if (window.confirm('Are you sure you want to delete this draft?')) {
            deleteMutation.mutate(selectedPost.id);
        }
    };

    const handleUpload = async (e) => {
        const file = e.target.files[0];
        if (!file) return;

        const formData = new FormData();
        formData.append('image', file);

        setIsUploading(true);
        try {
            const res = await api.post(`/posts/${selectedPost.id}/upload-image`, formData);
            setSelectedPost(res.data);
            queryClient.invalidateQueries(['posts']);
            toast.success('Custom poster uploaded successfully');
        } catch (e) {
            toast.error('Upload failed: ' + e.message);
        } finally {
            setIsUploading(false);
        }
    };

    const handleRegenerate = async () => {
        setIsRegenerating(true);
        try {
            const res = await api.post(`/posts/${selectedPost.id}/regenerate-image`);
            setSelectedPost(res.data);
            queryClient.invalidateQueries(['posts']);
            toast.success('AI Image regenerated');
        } catch (e) {
            toast.error('Regeneration failed: ' + e.message);
        } finally {
            setIsRegenerating(false);
        }
    };
    const handleRecomposite = async () => {
        setIsRecompositing(true);
        try {
            const res = await api.post(`/posts/${selectedPost.id}/recomposite`);
            setSelectedPost(res.data);
            queryClient.invalidateQueries(['posts']);
            toast.success('Professional Poster updated!');
        } catch (e) {
            toast.error('Design update failed: ' + e.message);
        } finally {
            setIsRecompositing(false);
        }
    };

    const safeDate = (val) => {
        const d = new Date(val);
        return isNaN(d) ? '—' : format(d, 'MMM d, ha');
    };

    const getPlatformIcon = (plt) => {
        return <SocialIcon platform={plt} size={16} />;
    }

    return (
        <div className="max-w-7xl mx-auto space-y-6 text-slate-900">
            <div className="flex justify-between items-center bg-white p-5 rounded-xl shadow-sm border border-slate-100 mb-6">
                <div className="flex items-center gap-4">
                    <div>
                        <h1 className="text-xl font-bold bg-gradient-to-r from-slate-900 to-slate-700 bg-clip-text text-transparent uppercase tracking-[0.2em]">Draft Intelligence</h1>
                        <p className="text-[10px] text-slate-500 font-bold uppercase tracking-widest">Review & Deployment Pipeline</p>
                    </div>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
                {/* Draft List Sidebar */}
                <div className="lg:col-span-1 bg-white rounded-xl p-4 shadow-sm border border-slate-100 h-[calc(100vh-140px)] flex flex-col">
                    <div className="flex items-center justify-between mb-6 px-2">
                        <h2 className="text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em]">Queue ({drafts.length})</h2>
                        <div className="w-2 h-2 rounded-full bg-amber-400 animate-pulse"></div>
                    </div>

                    <div className="flex-1 overflow-y-auto pr-2 custom-scrollbar">
                        {isLoading ? (
                            <div className="p-5 text-center text-slate-300 font-bold tracking-widest uppercase text-[10px]">Syncing Drafts...</div>
                        ) : drafts.length === 0 ? (
                            <div className="p-12 text-center text-slate-400 border-4 border-dashed border-slate-50 rounded-xl flex flex-col items-center">
                                <Sparkles size={32} className="mb-4 opacity-10" />
                                <span className="text-sm font-bold">Queue Empty</span>
                            </div>
                        ) : (
                            <div className="space-y-4">
                                {drafts.map(post => (
                                    <div
                                        key={post.id}
                                        onClick={() => { setSelectedPost(post); setIsEditing(false); }}
                                        className={`p-5 rounded-xl cursor-pointer transition-all border-2 relative group ${selectedPost?.id === post.id ? 'bg-indigo-50 border-blue-200 shadow-md transform -translate-y-1' : 'bg-white border-slate-50 hover:border-slate-100'}`}
                                    >
                                        <div className="flex justify-between items-start mb-3">
                                            <div
                                                className="p-2.5 rounded-lg flex items-center justify-center transition-colors"
                                                style={{
                                                    backgroundColor: `${getBrandColor(post.platform)}15`,
                                                    color: getBrandColor(post.platform),
                                                    border: `1px solid ${getBrandColor(post.platform)}30`
                                                }}
                                            >
                                                {getPlatformIcon(post.platform)}
                                            </div>
                                            <div className="flex flex-col items-end">
                                                <span className="text-[10px] font-black uppercase tracking-[0.15em] mb-0.5" style={{ color: getBrandColor(post.platform) }}>
                                                    {post.platform === 'google_business' ? 'Google Business' : post.platform}
                                                </span>
                                                <span className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">{safeDate(post.created_at || post.createdAt)}</span>
                                            </div>
                                        </div>
                                        <h3 className="text-xs font-bold text-slate-900 mb-1.5 line-clamp-1 group-hover:text-blue-600 transition-colors">{post.topic}</h3>

                                        {post.image_url ? (
                                            <div className="flex items-center gap-2 text-[9px] text-emerald-600 font-bold uppercase tracking-widest bg-emerald-50 w-max px-2.5 py-1.5 rounded-lg border border-emerald-100">
                                                <ImageIcon size={12} /> Ready
                                            </div>
                                        ) : (
                                            <div className="flex items-center gap-2 text-[9px] text-amber-600 font-bold uppercase tracking-widest bg-amber-50 w-max px-2.5 py-1.5 rounded-lg border border-amber-100">
                                                <Loader2 size={12} className="animate-spin" /> Rendering
                                            </div>
                                        )}
                                        <ChevronRight size={16} className={`absolute right-4 bottom-5 transition-all ${selectedPost?.id === post.id ? 'text-indigo-300 translate-x-0 opacity-100' : 'text-slate-100 -translate-x-2 opacity-0'}`} />
                                    </div>
                                ))}
                            </div>
                        )}
                    </div>
                </div>

                {/* Detail View */}
                <div className="lg:col-span-2 relative">
                    {selectedPost ? (
                        <div className="bg-white rounded-xl overflow-hidden shadow-sm border border-slate-100 flex flex-col ">
                            <div className="p-4 border-b border-slate-50 bg-slate-50/30 flex flex-col gap-3">
                                {/* Header Level 1: Meta + Secondary Actions */}
                                <div className="flex justify-between items-center">
                                    <div className="flex items-center gap-2">
                                        <div className={`p-1.5 rounded-lg bg-white shadow-sm border border-slate-100 ${selectedPost.platform === 'facebook' ? 'text-blue-600' :
                                            selectedPost.platform === 'instagram' ? 'text-pink-600' :
                                            selectedPost.platform === 'google_business' ? 'text-blue-500' :
                                                'text-sky-600'
                                            }`}>
                                            {getPlatformIcon(selectedPost.platform)}
                                        </div>
                                        <span className="px-2 py-0.5 bg-white border border-slate-200 rounded text-[9px] font-bold uppercase tracking-widest text-slate-500">
                                            {selectedPost.platform === 'google_business' ? 'Google Business' : selectedPost.platform} Pipeline
                                        </span>
                                    </div>
                                    <div className="flex gap-2">
                                        <button
                                            onClick={() => setShowRefineModal(true)}
                                            className="p-3 bg-white hover:bg-slate-900 hover:text-white text-blue-500 rounded-xl border border-slate-100 shadow-xl transition-all relative group"
                                            title="Edit with AI"
                                        >
                                            <Sparkles size={18} fill="currentColor" className="opacity-20 group-hover:opacity-100" />
                                            <div className="absolute -top-1 -right-1 w-2 h-2 bg-blue-500 rounded-full animate-ping"></div>
                                        </button>
                                        <button onClick={startEdit} className="p-3 bg-white hover:bg-slate-900 hover:text-white text-slate-400 rounded-xl border border-slate-100 shadow-xl transition-all" title="Edit">
                                            <Pencil size={18} />
                                        </button>
                                        <button onClick={handleDelete} className="p-3 bg-white hover:bg-rose-600 hover:text-white text-slate-400 rounded-xl border border-slate-100 shadow-xl transition-all" title="Delete">
                                            <Trash2 size={18} />
                                        </button>
                                    </div>
                                </div>

                                {/* Header Level 2: Title + Primary Actions */}
                                <div className="flex justify-between items-end gap-4 pb-1">
                                    <h2 className="text-xl font-bold text-slate-900 tracking-tight leading-tight flex-1 max-w-2xl">{selectedPost.topic}</h2>
                                    <div className="flex gap-2 flex-shrink-0">
                                        <button
                                            onClick={() => rejectMutation.mutate(selectedPost.id)}
                                            className="px-3 py-1.5 bg-white border border-slate-200 text-slate-500 hover:text-rose-600 hover:border-rose-200 rounded-lg font-bold text-[9px] uppercase tracking-widest transition-all shadow-sm flex items-center gap-2"
                                        >
                                            <XCircle size={14} strokeWidth={2} /> Reject
                                        </button>
                                        <button
                                            onClick={() => approveMutation.mutate(selectedPost.id)}
                                            disabled={approveMutation.isPending}
                                            className={`px-5 py-1.5 rounded-lg font-bold text-[9px] uppercase tracking-widest transition-all flex items-center gap-2 shadow-md ${
                                                scheduledAt 
                                                ? 'bg-emerald-600 hover:bg-slate-900 text-white shadow-emerald-100' 
                                                : 'bg-blue-600 hover:bg-slate-900 text-white shadow-blue-100'
                                            }`}
                                        >
                                            {approveMutation.isPending ? <Loader2 size={14} className="animate-spin" /> : <CheckCircle2 size={14} strokeWidth={2} />}
                                            {scheduledAt ? 'Schedule & Queue' : 'Approve Now'}
                                        </button>
                                    </div>
                                </div>
                            {/* Chronos Scheduling Row */}
                            <div className="px-5 py-3 border-b border-slate-50 bg-indigo-50/20 flex items-center justify-between gap-4">
                                <div className="flex items-center gap-2">
                                    <Clock size={14} className="text-slate-400" />
                                    <span className="text-[10px] font-bold text-slate-800 uppercase tracking-widest">Schedule Publication</span>
                                </div>
                                <div className="flex-1 max-w-xs relative group">
                                     <input 
                                        type="datetime-local" 
                                        value={scheduledAt}
                                        onChange={(e) => setScheduledAt(e.target.value)}
                                        className="w-full px-4 py-2 bg-white border border-indigo-100 rounded-lg outline-none focus:border-indigo-400 focus:ring-4 focus:ring-indigo-500/5 transition-all font-bold text-[11px] text-slate-700 shadow-sm"
                                     />
                                </div>
                                <div className="text-[9px] text-slate-400 font-medium italic">
                                    {scheduledAt 
                                        ? `Scheduled for ${new Date(scheduledAt).toLocaleString()}` 
                                        : "Approval will publish the post immediately."}
                                </div>
                            </div>
                            {/* Scrollable Content Area */}
                            <div className="flex-1 overflow-y-auto p-6 pb-32 space-y-8 bg-white custom-scrollbar">
                                <div>
                                    <div className="flex items-center gap-3 mb-4">
                                        <h3 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Post Copy / Caption</h3>
                                        <div className="h-px flex-1 bg-slate-50"></div>
                                    </div>
                                    <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100 whitespace-pre-wrap text-slate-600 text-sm leading-relaxed font-medium shadow-inner">
                                        {selectedPost.caption}
                                    </div>
                                </div>

                                    {selectedPost.poster_copy && (
                                        <div className="mt-8">
                                            <div className="flex items-center gap-3 mb-4">
                                                <h3 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Graphic Overlay</h3>
                                                <div className="h-px flex-1 bg-slate-50"></div>
                                            </div>
                                            <div className="relative group/overlay overflow-hidden">
                                                {/* Sophisticated Dark Accents */}
                                                <div className="absolute top-0 right-0 w-32 h-32 bg-indigo-500/10 rounded-full blur-3xl -mr-16 -mt-16"></div>
                                                <div className="absolute bottom-0 left-0 w-32 h-32 bg-blue-500/10 rounded-full blur-3xl -ml-16 -mb-16"></div>

                                                <div className="bg-slate-950 p-10 border-2 border-slate-800/50 rounded-[2.5rem] flex flex-col gap-6 text-center relative shadow-2xl hover:border-indigo-500/30 transition-all duration-500">
                                                    {/* Elite Design Makers */}
                                                    <div className="absolute top-6 left-6 w-4 h-4 border-t-2 border-l-2 border-slate-700 rounded-tl-sm"></div>
                                                    <div className="absolute bottom-6 right-6 w-4 h-4 border-b-2 border-r-2 border-slate-700 rounded-br-sm"></div>

                                                    {(() => {
                                                        const text = selectedPost.poster_copy || '';
                                                        const mainMatch = text.match(/MAIN HEADLINE:\s*(.*?)(?=SUBHEADLINE:|$)/si);
                                                        const subMatch = text.match(/SUBHEADLINE:\s*(.*)/si);
                                                        
                                                        const main = mainMatch ? mainMatch[1].trim() : text;
                                                        const sub = subMatch ? subMatch[1].trim() : '';

                                                        return (
                                                            <>
                                                                <div className="space-y-2">
                                                                    <div className="text-[10px] font-black text-indigo-400 uppercase tracking-[0.4em] mb-4 opacity-80">Headline</div>
                                                                    <div className="text-white text-2xl font-black uppercase tracking-tight leading-[1.1] drop-shadow-md">
                                                                        {main}
                                                                    </div>
                                                                </div>
                                                                
                                                                {sub && (
                                                                    <div className="pt-6 border-t border-slate-800">
                                                                        <div className="text-[10px] font-black text-slate-500 uppercase tracking-[0.4em] mb-3 opacity-60">Subtext</div>
                                                                        <div className="text-slate-400 font-bold text-xs uppercase tracking-[0.2em] leading-relaxed max-w-sm mx-auto">
                                                                            {sub}
                                                                        </div>
                                                                    </div>
                                                                )}
                                                            </>
                                                        );
                                                    })()}
                                                </div>
                                            </div>
                                        </div>
                                    )}
                                </div>

                                <div>
                                    <div className="flex items-center gap-3 mb-4">
                                        <h3 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Professional Poster</h3>
                                        <div className="h-px flex-1 bg-slate-50"></div>
                                        <div className="flex gap-2">
                                            <input
                                                type="file"
                                                ref={fileInputRef}
                                                onChange={handleUpload}
                                                className="hidden"
                                                accept="image/*"
                                            />
                                            <button
                                                onClick={() => fileInputRef.current.click()}
                                                disabled={isUploading}
                                                className="p-1.5 text-slate-400 hover:text-blue-600 transition-colors"
                                                title="Upload Custom Poster"
                                            >
                                                <Upload size={14} />
                                            </button>
                                            <button
                                                onClick={handleRecomposite}
                                                disabled={isRecompositing || isRegenerating || isUploading}
                                                className="p-1.5 text-slate-400 hover:text-emerald-600 transition-colors"
                                                title="Refresh Graphics Overlay"
                                            >
                                                <Palette size={14} className={isRecompositing ? 'animate-spin' : ''} />
                                            </button>
                                            <button
                                                onClick={handleRegenerate}
                                                disabled={isRegenerating || isUploading || isRecompositing}
                                                className="p-1.5 text-slate-400 hover:text-indigo-600 transition-colors"
                                                title="Regenerate AI Background"
                                            >
                                                <Zap size={14} className={isRegenerating ? 'animate-pulse' : ''} />
                                            </button>
                                        </div>
                                    </div>

                                    {isUploading || isRegenerating ? (
                                        <div className="h-64 rounded-3xl border-4 border-dashed border-indigo-100 bg-indigo-50/30 flex flex-col items-center justify-center text-indigo-400">
                                            <Loader2 size={40} className="animate-spin mb-4" />
                                            <span className="font-bold text-[10px] uppercase tracking-widest">
                                                {isUploading ? 'Uploading custom asset...' : 'Generating AI visual...'}
                                            </span>
                                        </div>
                                    ) : selectedPost.image_url ? (
                                        <div 
                                            className="rounded-3xl overflow-hidden shadow-2xl border-4 border-white bg-slate-100 group relative cursor-zoom-in"
                                            onClick={() => setShowFullImage(true)}
                                        >
                                            <img src={`http://localhost:3001${selectedPost.image_url}`} alt="Generated Creative" className="w-full block" />
                                            <div className="absolute top-4 right-4 bg-black/50 text-white p-2 rounded-full opacity-0 group-hover:opacity-100 transition-opacity backdrop-blur-md">
                                                <Maximize2 size={16} />
                                            </div>
                                        </div>
                                    ) : (
                                        <div className="rounded-3xl shadow-2xl border-4 border-white bg-slate-900 aspect-[4/5] relative flex flex-col justify-end p-8 overflow-hidden group">
                                            {/* Typography Mockup (Review Phase) */}
                                            <div className="absolute top-10 left-8">
                                                <div className="w-12 h-1 bg-indigo-500 mb-4 opacity-50 shadow-[0_0_10px_rgba(99,102,241,0.3)]"></div>
                                                <p className="text-white/20 text-[10px] font-bold uppercase tracking-[0.4em] mb-1">Copy Review Mode</p>
                                                <p className="text-white/10 text-[8px] font-bold uppercase tracking-widest leading-relaxed max-w-[200px]">
                                                    Background will be generated upon approval
                                                </p>
                                            </div>

                                            <div className="relative z-10 mb-20 animate-in slide-in-from-bottom-4 duration-700">
                                                {(() => {
                                                    const text = selectedPost.poster_copy || '';
                                                    const headlineMatch = text.match(/HEADLINE:\s*(.*?)(?=SUBTEXT:|POINTS:|BIG_NUMBER:|$)/si);
                                                    const subtextMatch = text.match(/SUBTEXT:\s*(.*)/si);
                                                    const pointsMatch = text.match(/POINTS:\s*(.*)/si);
                                                    
                                                    const headline = headlineMatch ? headlineMatch[1].trim() : text.replace(/STYLE: \w+/i, '').trim() || 'Awaiting Content...';
                                                    const subheadline = subtextMatch ? subtextMatch[1].trim() : (pointsMatch ? '• ' + pointsMatch[1].split(';')[0].trim() : '');
                                                    
                                                    return (
                                                        <div className="space-y-4">
                                                            <div className="w-12 h-1.5 bg-indigo-500 shadow-[0_0_15px_rgba(99,102,241,0.5)]"></div>
                                                            <h2 className="text-4xl md:text-5xl font-black text-white leading-[0.9] tracking-tighter uppercase line-clamp-4 mix-blend-difference">
                                                                {headline}
                                                            </h2>
                                                            <p className="text-indigo-400 font-bold text-sm tracking-wide uppercase">
                                                                {subheadline}
                                                            </p>
                                                        </div>
                                                    );
                                                })()}
                                            </div>

                                            {/* Action Overlay */}
                                            <div className="absolute inset-0 bg-indigo-600/20 backdrop-blur-sm opacity-0 group-hover:opacity-100 transition-all duration-500 flex items-center justify-center p-8 text-center">
                                                <div className="space-y-6">
                                                    <div className="w-20 h-20 rounded-[30px] bg-white text-indigo-600 flex items-center justify-center shadow-2xl mx-auto transform group-hover:scale-110 transition-transform duration-500">
                                                        <Sparkles size={32} className="animate-pulse" />
                                                    </div>
                                                    <div>
                                                        <p className="text-white font-black text-xl uppercase tracking-tighter">Ready for Design?</p>
                                                        <p className="text-white/60 text-[10px] font-bold uppercase tracking-widest mt-1">Generate AI Background for this copy</p>
                                                    </div>
                                                    <div className="flex gap-3 justify-center">
                                                        <button
                                                            onClick={handleRegenerate}
                                                            className="flex-1 py-4 px-8 rounded-2xl bg-white text-indigo-600 font-black text-[10px] uppercase tracking-widest hover:bg-slate-50 transition-all flex items-center justify-center gap-2"
                                                        >
                                                            <Zap size={14} /> <span>Generate</span>
                                                        </button>
                                                        <button
                                                            onClick={() => fileInputRef.current.click()}
                                                            className="py-4 px-6 rounded-2xl bg-white/20 text-white font-black text-[10px] uppercase tracking-widest hover:bg-white/40 backdrop-blur-md transition-all flex items-center justify-center"
                                                        >
                                                            <Upload size={14} />
                                                        </button>
                                                    </div>
                                                </div>
                                            </div>

                                            {/* Empty State Instructions */}
                                            <div className="absolute inset-0 flex items-center justify-center pointer-events-none group-hover:hidden transition-opacity">
                                                <div className="flex flex-col items-center gap-4">
                                                    <div className="w-16 h-16 rounded-full border-2 border-dashed border-white/20 flex items-center justify-center">
                                                        <Zap size={24} className="text-white/20" />
                                                    </div>
                                                    <p className="text-white/20 text-[10px] font-black uppercase tracking-[0.2em]">Pending Generation</p>
                                                </div>
                                            </div>
                                        </div>
                                    )}

                                    <div className="mt-8">
                                        <div className="flex items-center gap-3 mb-4">
                                            <h3 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Strategy Log</h3>
                                            <div className="h-px flex-1 bg-slate-50"></div>
                                        </div>
                                        <div className="bg-slate-900 p-4 rounded-3xl text-emerald-400 text-[9px] overflow-hidden border border-slate-800 font-mono shadow-2xl relative">
                                            <div className="absolute top-0 right-0 p-3 flex gap-1">
                                                <div className="w-2 h-2 rounded-full bg-slate-800"></div>
                                                <div className="w-2 h-2 rounded-full bg-slate-800"></div>
                                                <div className="w-2 h-2 rounded-full bg-slate-800"></div>
                                            </div>
                                            <pre className="whitespace-pre-wrap">
                                                {selectedPost.strategy_notes ? JSON.stringify(JSON.parse(selectedPost.strategy_notes), null, 2) : 'No audit log found.'}
                                            </pre>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {isEditing && (
                                <div className="absolute inset-0 bg-white/98 z-30 flex flex-col p-12 backdrop-blur-xl animate-in fade-in zoom-in-95">
                                    <div className="flex items-center gap-4 mb-10">
                                        <div className="w-12 h-12 rounded-xl bg-indigo-50 text-blue-600 flex items-center justify-center">
                                            <Pencil size={24} />
                                        </div>
                                        <div>
                                            <h2 className="text-3xl font-bold text-slate-900 tracking-tight">Polish Draft</h2>
                                            <p className="text-slate-400 font-medium">Fine-tune the copy and hook for maximum conversion.</p>
                                        </div>
                                    </div>

                                    <div className="space-y-8 flex-1 overflow-y-auto pr-6 custom-scrollbar">
                                        <div className="space-y-3">
                                            <label className="text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em] px-1">Engagement Caption</label>
                                            <textarea rows="12" className="w-full p-4 bg-slate-50 border-2 border-slate-100 rounded-xl focus:ring-4 focus:ring-blue-500/10 focus:border-indigo-500 outline-none text-sm font-medium text-slate-700 leading-relaxed shadow-inner" value={editData.caption} onChange={e => setEditData({ ...editData, caption: e.target.value })} />
                                        </div>
                                        <div className="space-y-3">
                                            <label className="text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em] px-1">Graphic Headline Hook</label>
                                            <div className="relative">
                                                <Sparkles className="absolute left-6 top-1/2 -translate-y-1/2 text-amber-400" size={18} />
                                                <input type="text" className="w-full pl-14 pr-6 py-5 bg-slate-50 border-2 border-slate-100 rounded-xl focus:ring-4 focus:ring-blue-500/10 focus:border-indigo-500 outline-none font-bold text-slate-800 shadow-inner" value={editData.poster_copy} onChange={e => setEditData({ ...editData, poster_copy: e.target.value })} />
                                            </div>
                                        </div>
                                    </div>

                                    <div className="flex justify-end gap-3 pt-10 border-t border-slate-50 mt-10">
                                        <button onClick={() => setIsEditing(false)} className="px-10 py-4 bg-slate-100 text-slate-600 rounded-xl font-bold text-[11px] uppercase tracking-widest">Discard</button>
                                        <button onClick={() => updateMutation.mutate(editData)} className="px-12 py-4 bg-blue-600 text-white rounded-xl font-bold text-[11px] uppercase tracking-widest shadow-2xl shadow-blue-200 hover:bg-slate-900 transition-all">Lock in Changes</button>
                                    </div>
                                </div>
                            )}
                        </div>
                    ) : (
                        <div className="h-[800px] bg-white rounded-xl border-4 border-dashed border-slate-50 flex flex-col items-center justify-center text-slate-200">
                            <div className="w-24 h-24 rounded-full bg-slate-50 flex items-center justify-center mb-6">
                                <Sparkles size={48} className="opacity-20" />
                            </div>
                            <span className="font-bold text-xl text-slate-400 tracking-tight">Select draft to polish</span>
                            <span className="text-sm font-medium text-slate-300 mt-2 max-w-[200px] text-center">Approve them to send them live on the calendar.</span>
                        </div>
                    )}
                </div>
            </div>

            {/* AI Polish Modal */}
            {showRefineModal && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-6 bg-slate-900/60 backdrop-blur-xl animate-in fade-in duration-300">
                    <div className="bg-white rounded-[40px] shadow-2xl border border-slate-100 w-full max-w-lg overflow-hidden animate-in zoom-in-95 duration-300">
                        <div className="p-10 pb-6 text-center">
                            <div className="w-20 h-20 rounded-[30px] bg-indigo-50 flex items-center justify-center text-indigo-600 mx-auto mb-6 shadow-inner ring-8 ring-indigo-50/50">
                                <Sparkles size={32} className="animate-pulse" />
                            </div>
                            <h2 className="text-2xl font-black text-slate-900 tracking-tight mb-2">Refine Design & Copy</h2>
                            <p className="text-sm text-slate-400 font-medium">AI will transform your strategy and visual concept based on your direction.</p>
                        </div>

                        <div className="px-10 pb-10 space-y-6">
                            <div className="space-y-3">
                                <label className="text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em] px-1">Specific Direction (Optional)</label>
                                <textarea
                                    className="w-full p-5 bg-slate-50 border-2 border-slate-100 rounded-[30px] focus:ring-4 focus:ring-indigo-500/10 focus:border-indigo-500 outline-none text-sm font-medium text-slate-700 leading-relaxed shadow-inner placeholder:text-slate-300 min-h-[140px] transition-all"
                                    placeholder="E.g. 'Make it shorter', 'Change the background to a nursing station', 'Add more medical emojis'..."
                                    value={instruction}
                                    onChange={e => setInstruction(e.target.value)}
                                />
                            </div>

                            <div className="flex flex-wrap gap-2">
                                {[
                                    { label: 'Punchier Hook', value: 'Make the hook more aggressive and punchy' },
                                    { label: 'Visual Refresh', value: 'Change the background to something more modern and premium' },
                                    { label: 'Expressive', value: 'Add more emojis and human energy' },
                                    { label: 'Clinical Elite', value: 'Make the tone more professional and clinical' }
                                ].map(tag => (
                                    <button
                                        key={tag.label}
                                        onClick={() => setInstruction(tag.value)}
                                        className="px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-600 rounded-full text-[10px] font-bold uppercase tracking-wider transition-all"
                                    >
                                        {tag.label}
                                    </button>
                                ))}
                            </div>

                            <div className="flex gap-4 pt-4">
                                <button
                                    onClick={() => { setShowRefineModal(false); setInstruction(''); }}
                                    className="flex-1 py-5 px-6 rounded-[25px] bg-white border-2 border-slate-100 text-slate-500 font-bold text-[11px] uppercase tracking-widest hover:bg-slate-50 transition-all"
                                >
                                    Nevermind
                                </button>
                                <button
                                    onClick={() => refineMutation.mutate({ instruction })}
                                    disabled={refineMutation.isPending}
                                    className="flex-[2] py-5 px-6 rounded-[25px] bg-indigo-600 text-white font-bold text-[11px] uppercase tracking-widest shadow-xl shadow-indigo-100 hover:bg-slate-900 transition-all flex items-center justify-center gap-3 disabled:opacity-50 disabled:cursor-not-allowed"
                                >
                                    {refineMutation.isPending ? (
                                        <>
                                            <Loader2 size={16} className="animate-spin" />
                                            <span>Processing Update...</span>
                                        </>
                                    ) : (
                                        <>
                                            <Sparkles size={16} />
                                            <span>Refine Intelligence</span>
                                        </>
                                    )}
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            )}

            {/* Full Image Modal */}
            {showFullImage && (
                <div className="fixed inset-0 z-[100] bg-slate-950/95 backdrop-blur-xl flex flex-col items-center justify-center p-4 md:p-10 animate-in fade-in duration-300">
                    <button 
                        onClick={() => setShowFullImage(false)}
                        className="absolute top-10 right-10 text-white/50 hover:text-white transition-colors"
                    >
                        <X size={40} />
                    </button>
                    <div className="max-w-4xl w-full h-full flex flex-col justify-center items-center gap-6">
                        <img 
                            src={`http://localhost:3001${selectedPost.image_url}`} 
                            alt="Full Resolution Poster" 
                            className="max-h-[85vh] w-auto rounded-2xl shadow-[0_0_100px_rgba(0,0,0,0.5)] border-4 border-white/10"
                        />
                        <div className="text-center">
                            <h2 className="text-white font-bold text-xl uppercase tracking-widest mb-2">High Resolution Preview</h2>
                            <p className="text-white/40 text-xs uppercase tracking-[0.4em]">1080 x 1350 • Professional Asset</p>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
